name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp -r create_notion_task query_notion_task lambda_function.py package/
          cd package
          zip -r ../function.zip .

      - name: Deploy Lambda to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          aws lambda update-function-code \
            --function-name NotionSyncGCal \
            --zip-file fileb://function.zip
